apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
spec:
  containers:
    - name: nginx
      image: my-registry:30000/mynginx:v1  # Private registry and image
      resources: {}
  dnsPolicy: ClusterFirst
  imagePullSecrets:
    - name: nginx-secret  # Secret to pull from private registry
  restartPolicy: Always
status: {}
