apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
spec:
  containers:
    - name: nginx
      image: my-registry:5000/mynginx:v3  # Private registry and image
      ports:
        - containerPort: 80
  imagePullSecrets:
    - name: nginx-secret  # Secret to pull from private registry
