# helmfile.yaml
repositories:
  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts
    
releases:
  - name: prometheus
    namespace: monitoring
    chart: prometheus-community/prometheus
    version: "14.8.0"
    values:
      - values-prometheus.yaml
    set:
      - name: replicaCount
        value: 3
    hooks:
      - events: ["prepare"]
        command: "./pre-deploy-prometheus.sh"
        showlogs: true