# helmfile.yaml
repositories:
  - name: prometheus
    url: https://prometheus-community.github.io/helm-charts
  - name: bitnami
    url: https://charts.bitnami.com/bitnami

releases:
  - name: prometheus
    namespace: monitoring
    chart: prometheus-community/prometheus
    version: "14.8.0"
    values:
      - values-prometheus.yaml
    set:
      - name: replicaCount
        value: 3
    hooks:
      - events: ["prepare"]
        command: "./pre-deploy-prometheus.sh"
        showlogs: true

  - name: nginx
    namespace: web
    chart: bitnami/nginx
    version: "latest
    values:
      - values-nginx.yaml
    set:
      - name: image.tag
        value: "latest"
    hooks:
      - events: ["prepare"]
        command: "./pre-deploy-nginx.sh"
        showlogs: true
