repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami

# Define a template for Nginx releases
templates:
  default: &default
    chart: bitnami/nginx
    version: "9.1.0"  # Replace with the desired version
    values:
      - values-nginx.yaml  # Custom values file
    set:
      - name: image.tag
        value: "1.21.0"  # Override image tag
    hooks:
      - events: ["prepare"]
        command: "./pre-deploy-nginx.sh"
        showlogs: true

# Use the template to define multiple releases
releases:
  - name: nginx-main
    namespace: web
    <<: *default  # Use the template for the main Nginx deployment

  - name: nginx-backup
    namespace: backup
    <<: *default  # Use the template for a backup Nginx deployment
    set:
      - name: replicaCount
        value: 2  # Override the 