# helmfile.yaml

repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
  - name: stable
    url: https://charts.helm.sh/stable

secrets:
  - values-secrets.yaml.enc  # Encrypted secrets file (e.g., using SOPS)

releases:
  - name: myapp
    chart: bitnami/nginx
    namespace: default
    values:
      - values.yaml           # Regular values file
      - values-secrets.yaml.enc  # Encrypted secrets file