repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami

releases:
  - name: my-app
    chart: bitnami/my-chart  # Use the correct chart and repository
    values:
      - ./values.yaml
    secrets:
      - ./values-secrets-encrypted.yaml
