# helmfile.yaml

repositories:
  - name: stable
    url: https://charts.helm.sh/stable
  - name: bitnami
    url: https://charts.bitnami.com/bitnami

templates:
  default: &default
    replicaCount: 3
    image:
      repository: nginx
      tag: latest
    resources:
      limits:
        cpu: "500m"
        memory: "1Gi"
      requests:
        cpu: "250m"
        memory: "512Mi"

releases:
  - name: my-nginx
    namespace: default
    chart: stable/nginx
    values:
      - *default  # Reusing the 'default' template here
  - name: my-nginx-prod
    namespace: prod
    chart: stable/nginx
    values:
      - replicaCount: 5  # Overriding the replicaCount for this release
      - *default  # Reusing the default template