repositories:
  - name: stable
    url: https://charts.helm.sh/stable
  - name: bitnami
    url: https://charts.bitnami.com/bitnami

# Define reusable value blocks using YAML anchors
commonValues: &defaultValues
  replicaCount: 3
  image:
    repository: nginx
    tag: latest
  resources:
    requests:
      cpu: "250m"
      memory: "512Mi"

releases:
  - name: my-nginx
    namespace: default
    chart: stable/nginx
    values:
      - *defaultValues  # Reusing the default values block
  - name: my-nginx-prod
    namespace: prod
    chart: stable/nginx
    values:
      - replicaCount: 5  # Overriding the replicaCount for this release
      - *defaultValues  # Reusing the default values block
