# values-nginx.yaml
controller:
  replicaCount: 3
  service:
    type: LoadBalancer
  ingress:
    enabled: true
    hosts:
      - name: nginx.example.com
        paths:
          - /
    annotations:
      kubernetes.io/ingress.class: "nginx"

image:
  repository: nginx
  tag: "latest"

resources:
  requests:
    memory: "64Mi"
    cpu: "250m"
  limits:
    memory: "128Mi"
    cpu: "500m"

persistence:
  enabled: true
  size: 8Gi
