version: '3.8'

services:
  usermanagementservice:
    image: ${IMAGE_NAME}:${DEMO_VERSION}-usermanagementservice
    container_name: usermanagementservice
    network_mode: "host"  # Use host network to connect to existing postgres
    ports:
      - "${USER_SVC_PORT}:${USER_SVC_PORT}"
    environment:
      - USER_SVC_URL=${USER_SVC_PORT}
      - JWT_SECRET=${JWT_SECRET}
      - OTEL_EXPORTER_OTLP_ENDPOINT=${OTEL_EXPORTER_OTLP_ENDPOINT}
      - DB_CONN=${DB_CONN}
    healthcheck:
      test: ["CMD", "/bin/grpc_health_probe", "-addr=localhost:${USER_SVC_PORT}"]
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 10s