version: '3.8'

services:
  usermanagementservice:
    build:
      context: ../../  # Root of the project
      dockerfile: ./src/usermanagementservice/Dockerfile
    container_name: usermanagementservice
    ports:
      - "8082"  # Map external port 8082 to internal port 8080
    environment:
      - USER_SVC_URL=:8082
      - JWT_SECRET=your-secure-jwt-secret
      - OTEL_EXPORTER_OTLP_ENDPOINT=otel-collector:4317
      - DB_CONN=postgres://postgres:postgres@postgres:5432/postgres?sslmode=disable
      - ENABLE_MIGRATIONS=true
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
        reservations:
          cpus: '0.1'
          memory: 128M
    healthcheck:
      test: ["/bin/grpc_health_probe", "-addr=localhost:8082"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 15s
    restart: unless-stopped

