# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0
name: Gradle wrapper validation
on:
  pull_request:
    paths:
      - 'opentelemetry-demo/**/gradle/wrapper/**'

jobs:
  validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: gradle/actions/wrapper-validation@v4.3.0
