repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami

releases:
  - name: myapp
    chart: bitnami/nginx
    namespace: default
    values:
      - values.yaml            # Regular values file
    secrets:
      - ./values-secrets-encrypted.yaml
