# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0
name: Checks

on:
  push:
    branches: [main]
    paths:
      - 'opentelemetry-demo/**'
  pull_request:
    branches: [main]
    paths:
      - 'opentelemetry-demo/**'
  workflow_dispatch:

jobs:
  build_images:
    uses: opentelemetry-demo/component-build-images.yml
    with:
      push: false
      version: 'dev'

  markdownlint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: opentelemetry-demo
    steps:
      - name: check out code
        uses: actions/checkout@v4
      - name: install dependencies
        run: npm install
      - name: run markdownlint
        run: make markdownlint
