name: Test Database Service

on:
  push:
    # Only trigger on branches other than main
    branches-ignore:
      - main
    paths:
      # Include changes to the db directory
      - 'opentelemetry-demo/src/db/**'
      # But exclude test files so changes to tests don't trigger the workflow
      - '!opentelemetry-demo/src/db/test/**'
      - '!opentelemetry-demo/src/db/testutils/**'
      - '!opentelemetry-demo/src/db/**/*_test.go'
  # Manual triggering
  workflow_dispatch:
    inputs:
      test_scope:
        description: 'Scope of tests to run'
        required: true
        default: 'unit'
        type: choice
        options:
          - unit
          - setup
      debug_enabled:
        description: 'Enable debug mode'
        required: false
        default: false
        type: boolean

jobs:
  test:
    name: Run Database Tests
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
          cache: true

      # Add Docker Hub login to avoid rate limiting
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      # Install standalone docker-compose binary
      - name: Install docker-compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.23.3/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      - name: Debug Info
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.debug_enabled == true }}
        run: |
          echo "Running in debug mode"
          echo "Go version: $(go version)"
          echo "Directory structure:"
          find opentelemetry-demo/src/db -type f | sort


      - name: Set test type
        id: set-test-type
        run: |
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            echo "TEST_SCOPE=${{ inputs.test_scope }}" >> $GITHUB_ENV
          else
            echo "TEST_SCOPE=all" >> $GITHUB_ENV
          fi
          
      # Run unit tests
      - name: Run unit tests
        # Run if pushed or when manually triggered with unit or all scope
        if: ${{ env.TEST_SCOPE == 'unit' }}
        run: cd opentelemetry-demo && make db-unittest

      # Run setup tests
      - name: Run setup test
        # Run if manually triggered with setup or all scope
        if: ${{ env.TEST_SCOPE == 'setup' }}
        run: cd opentelemetry-demo && make db-setup-test

      - name: Run all tests
        if: ${{ env.TEST_SCOPE == 'all' }}
        run: cd opentelemetry-demo && make db-unittest && make db-setup-test